[versions]
kotlin = "2.3.10"
publishing = "2.0.0"
kotlinpoet = "2.2.0"
javapoet = "1.13.0"
testcontainers = "1.21.4"
postgresql = "42.7.9"
mariadb = "3.5.7"
mysql = "9.6.0"
jimmer = "0.10.6"
jspecify = "1.0.0"
jackson = "2.21.0"
h2 = "2.4.240"
asm = "9.9.1"

[libraries]
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jimmer = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }
jimmer-dto-compiler = { module = "org.babyfish.jimmer:jimmer-dto-compiler", version.ref = "jimmer" }
jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "publishing" }